export const START_GAME = "START_GAME"
export const END_GAME = "END_GAME"
export const RESET_GAME = "RESET_GAME"
export const PERFORM_MOVE = "PERFORM_MOVE"
export const TICK = "TICK"
export const ACTIVATE_MOLE = "ACTIVATE_MOLE"
export const DEACTIVATE_MOLE = "DEACTIVATE_MOLE"
export const INCREASE_SCORE = "INCREASE_SCORE"